#!/bin/bash

# Universal bash script used to start Nodes.
# Copy as Node[NodeName] to folder in $PATH
# and make executable.
# Adjust PAT_SOCCER to git repo

PATH_SOCCER=~/ProjTurtleBot/soccer/
NODE_NAME=$(basename "$0")


cd $PATH_SOCCER$NODE_NAME

python $NODE_NAME".py" "$@"
